spring:
  application:
    name: ProductStorage-Back
    version: 0.0.1-SNAPSHOT
    description: Aplicação backend para o sistema de controle de estoque ProductStorage

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  main:
    banner-mode: console

logging:
  level:
    org.springframework: warn

swagger:
  title: ${info.app.name:ProductStorage-Back}
  description: ${info.app.description:Aplicação backend}
  version: ${info.app.version:0.0.1-SNAPSHOT}
  servers:
    - url: http://localhost:8080
      description: Ambiente local
    - url: https://prd-strg-back.onrender.com
      description: Ambiente de produção

server:
  port: 8080

cors:
  allowed-origins: ${ALLOWED_ORIGINS:https://product-storage-front-gold.vercel.app}

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: info, health, prometheus
  info:
    env:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

info:
  app:
    name: ${spring.application.name}
    version: ${spring.application.version}
    description: ${spring.application.description}
  build:
    timestamp: ${maven.build.timestamp:2025-10-30T00:00:00Z}
  environment:
    profile: prod
    java:
      version: ${java.version}
    os:
      name: ${os.name}
      arch: ${os.arch}
