# =====================================
# Application generic config
# =====================================
spring:
  application:
    name: ProductStorage-Back
    version: 0.0.1-SNAPSHOT
    description: Aplicação backend para o sistema de controle de estoque ProductStorage

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: a3
    password: "123"

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    banner-mode: console

logging:
  level:
    org.springframework: info

# =====================================
# Swagger config
# =====================================
swagger:
  title: ${info.app.name:ProductStorage-Back}
  description: ${info.app.description:Aplicação backend}
  version: ${info.app.version:0.0.1-SNAPSHOT}
  terms-of-service-url: "http://localhost:8080/terms"
  license-name: MIT
  license-url: https://opensource.org/license/mit
  contact:
    name: "Pedro Nieto"
    url: "https://github.com/Pedroo-Nietoo"
    email: "pedronieto.2005@gmail.com"
  servers:
    - url: http://localhost:8080
      description: Ambiente local
    - url: https://staging-api.productstorage.com
      description: Ambiente de desenvolvimento
    - url: https://api.productstorage.com
      description: Ambiente de produção

# =====================================
# Server config
# =====================================
server:
  port: 8080

# =====================================
# Actuator + Management config
# =====================================
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: info, health, prometheus
  info:
    env:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# =====================================
# Application info metadata
# =====================================
info:
  app:
    name: ${spring.application.name}
    version: ${spring.application.version}
    description: ${spring.application.description}
  build:
    timestamp: ${maven.build.timestamp:2025-10-30T00:00:00Z}
  environment:
    profile: ${spring.profiles.active:local}
    java:
      version: ${java.version}
    os:
      name: ${os.name}
      arch: ${os.arch}